language: go
sudo: required
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y openssl build-essential xorg libssl-dev xfonts-75dpi; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget --quiet "https://builds.wkhtmltopdf.org/0.12.6-dev/wkhtmltox_0.12.6-0.20180618.3.dev.e6d6f54.bionic_amd64.deb" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo dpkg -i "wkhtmltox_0.12.6-0.20180618.3.dev.e6d6f54.bionic_amd64.deb" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then rm "wkhtmltox_0.12.6-0.20180618.3.dev.e6d6f54.bionic_amd64.deb" ; fi
go:
  - tip
  - 1.13
  - 1.12
script: go test -v -coverprofile=coverage.txt -covermode=atomic -bench .
os:
  - linux
dist: bionic
addons:
  artifacts: true
after_success:
  - bash <(curl -s https://codecov.io/bash)
